// This file was generated by script

import add from './add.svg';
import appstore from './appstore.svg';
import archived from './archived.svg';
import arrowBack from './arrow-back.svg';
import arrowDown from './arrow-down.svg';
import arrowLeft from './arrow-left.svg';
import arrowNext from './arrow-next.svg';
import arrowReceived from './arrow-received.svg';
import arrowRight from './arrow-right.svg';
import arrowSend from './arrow-send.svg';
import arrowSort from './arrow-sort.svg';
import arrowUp from './arrow-up.svg';
import calendar from './calendar.svg';
import chain from './chain.svg';
import chat from './chat.svg';
import circle from './circle.svg';
import close from './close.svg';
import code from './code.svg';
import copy from './copy.svg';
import dao from './dao.svg';
import dashboard from './dashboard.svg';
import defi from './defi.svg';
import edit from './edit.svg';
import expand from './expand.svg';
import exportIcon from './export-icon.svg';
import eyeClose from './eye-close.svg';
import eyeOpen from './eye-open.svg';
import favorite from './favorite.svg';
import follow from './follow.svg';
import global from './global.svg';
import governance from './governance.svg';
import history from './history.svg';
import home from './home.svg';
import link from './link.svg';
import load from './load.svg';
import logout from './logout.svg';
import mobile from './mobile.svg';
import more from './more.svg';
import notiErrorFilled from './noti-error-filled.svg';
import notiErrorStroke from './noti-error-stroke.svg';
import notiInfoFilled from './noti-info-filled.svg';
import notiInfoStroke from './noti-info-stroke.svg';
import notiRead from './noti-read.svg';
import notiSuccessFilled from './noti-success-filled.svg';
import notiSuccessStroke from './noti-success-stroke.svg';
import notiWarningFilled from './noti-warning-filled.svg';
import notiWarningStroke from './noti-warning-stroke.svg';
import notificationsDefault from './notifications-default.svg';
import open from './open.svg';
import payroll from './payroll.svg';
import placeholder from './placeholder.svg';
import pools from './pools.svg';
import preferences from './preferences.svg';
import pricing from './pricing.svg';
import priority from './priority.svg';
import privateIcon from './private-icon.svg';
import proposalsAdd from './proposals-add.svg';
import proposals from './proposals.svg';
import search from './search.svg';
import send from './send.svg';
import settings from './settings.svg';
import share from './share.svg';
import socialApple from './social-apple.svg';
import socialBehance from './social-behance.svg';
import socialDiscord from './social-discord.svg';
import socialDribbble from './social-dribbble.svg';
import socialEmail from './social-email.svg';
import socialFacebook from './social-facebook.svg';
import socialGithub from './social-github.svg';
import socialGitlab from './social-gitlab.svg';
import socialGoogle from './social-google.svg';
import socialInstagram from './social-instagram.svg';
import socialLinkedin from './social-linkedin.svg';
import socialMedium from './social-medium.svg';
import socialTelegram from './social-telegram.svg';
import socialTiktok from './social-tiktok.svg';
import socialTwitch from './social-twitch.svg';
import socialTwitter from './social-twitter.svg';
import socialYoutube from './social-youtube.svg';
import taskAdd from './task-add.svg';
import task from './task.svg';
import tax from './tax.svg';
import tick from './tick.svg';
import token from './token.svg';
import transfer from './transfer.svg';
import trash from './trash.svg';
import treasury from './treasury.svg';
import userAdd from './user-add.svg';
import userDelete from './user-delete.svg';
import userFeed from './user-feed.svg';
import userProfile from './user-profile.svg';
import users from './users.svg';
import viewBlock from './view-block.svg';
import viewHorizontal from './view-horizontal.svg';
import voteNo from './vote-no.svg';
import voteYes from './vote-yes.svg';
import vote from './vote.svg';
import voting from './voting.svg';
import wallet from './wallet.svg';
import yourDaos from './your-daos.svg';
import zero from './zero.svg';

const icons = {
  add,
  appstore,
  archived,
  'arrow-back': arrowBack,
  'arrow-down': arrowDown,
  'arrow-left': arrowLeft,
  'arrow-next': arrowNext,
  'arrow-received': arrowReceived,
  'arrow-right': arrowRight,
  'arrow-send': arrowSend,
  'arrow-sort': arrowSort,
  'arrow-up': arrowUp,
  calendar,
  chain,
  chat,
  circle,
  close,
  code,
  copy,
  dao,
  dashboard,
  defi,
  edit,
  expand,
  'export-icon': exportIcon,
  'eye-close': eyeClose,
  'eye-open': eyeOpen,
  favorite,
  follow,
  global,
  governance,
  history,
  home,
  link,
  load,
  logout,
  mobile,
  more,
  'noti-error-filled': notiErrorFilled,
  'noti-error-stroke': notiErrorStroke,
  'noti-info-filled': notiInfoFilled,
  'noti-info-stroke': notiInfoStroke,
  'noti-read': notiRead,
  'noti-success-filled': notiSuccessFilled,
  'noti-success-stroke': notiSuccessStroke,
  'noti-warning-filled': notiWarningFilled,
  'noti-warning-stroke': notiWarningStroke,
  'notifications-default': notificationsDefault,
  open,
  payroll,
  placeholder,
  pools,
  preferences,
  pricing,
  priority,
  'private-icon': privateIcon,
  'proposals-add': proposalsAdd,
  proposals,
  search,
  send,
  settings,
  share,
  'social-apple': socialApple,
  'social-behance': socialBehance,
  'social-discord': socialDiscord,
  'social-dribbble': socialDribbble,
  'social-email': socialEmail,
  'social-facebook': socialFacebook,
  'social-github': socialGithub,
  'social-gitlab': socialGitlab,
  'social-google': socialGoogle,
  'social-instagram': socialInstagram,
  'social-linkedin': socialLinkedin,
  'social-medium': socialMedium,
  'social-telegram': socialTelegram,
  'social-tiktok': socialTiktok,
  'social-twitch': socialTwitch,
  'social-twitter': socialTwitter,
  'social-youtube': socialYoutube,
  'task-add': taskAdd,
  task,
  tax,
  tick,
  token,
  transfer,
  trash,
  treasury,
  'user-add': userAdd,
  'user-delete': userDelete,
  'user-feed': userFeed,
  'user-profile': userProfile,
  users,
  'view-block': viewBlock,
  'view-horizontal': viewHorizontal,
  'vote-no': voteNo,
  'vote-yes': voteYes,
  vote,
  voting,
  wallet,
  'your-daos': yourDaos,
  zero,
};

export default icons;
