#!/bin/bash

# This script contains variables used in scripts that are for running locally

CONTAINER_NAME=pin-pfi-pg
RUNNING_CONTAINER=$(docker ps -aq --filter name=$CONTAINER_NAME --filter status=running)
STOPPED_CONTAINER=$(docker ps -aq --filter name=$CONTAINER_NAME --filter status=exited)
